import os
import sqlite3
import pandas as pd

# Project root se path (adapters -> src -> project root)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DEFAULT_DB_PATH = os.path.join(BASE_DIR, "data", "app.db")

MAX_RESULT_ROWS = 200 

class SQLiteService:
    """
    Handles structured (table) data — Excel uploads become SQLite tables,
    and this service lets us inspect their schema and run SELECT queries
    generated by the LLM.
    """

    def __init__(self, db_path: str = DEFAULT_DB_PATH):
        self._db_path = db_path
        os.makedirs(os.path.dirname(db_path), exist_ok=True)

    def _connect(self) -> sqlite3.Connection:
        return sqlite3.connect(self._db_path)

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """
        Makes a string safe to use as a SQLite table/column name —
        lowercase, spaces/special chars replaced with underscores.
        """
        name = name.strip().lower()
        name = "".join(c if c.isalnum() else "_" for c in name)
        while "__" in name:
            name = name.replace("__", "_")
        return name.strip("_")

    def create_table_from_excel(self, file_path: str, table_name: str) -> dict:
        """
        Reads an Excel file and loads it into a new SQLite table.
        Returns metadata about the created table (name, columns, row count).
        """
        df = pd.read_excel(file_path)
        df.columns = [self._sanitize_name(col) for col in df.columns]
        table_name = self._sanitize_name(table_name)

        conn = self._connect()
        try:
            df.to_sql(table_name, conn, if_exists="replace", index=False)
        finally:
            conn.close()

        columns_full = self.get_schema(table_name)  

        return {
            "table_name": table_name,
            "columns": columns_full,        
            "row_count": len(df),
        }

    def get_schema(self, table_name: str) -> list[dict]:
        """
        Returns column info for a table: [{"name": ..., "type": ...}, ...]
        Used to tell the LLM what columns are available when generating SQL.
        """
        conn = self._connect()
        try:
            cursor = conn.execute(f"PRAGMA table_info({table_name})")
            columns = cursor.fetchall()
        finally:
            conn.close()

        # PRAGMA table_info returns: (cid, name, type, notnull, dflt_value, pk)
        return [{"name": col[1], "type": col[2]} for col in columns]

    def get_row_count(self, table_name: str) -> int:
        """Returns the number of rows currently in a table."""
        conn = self._connect()
        try:
            cursor = conn.execute(f"SELECT COUNT(*) FROM {self._sanitize_name(table_name)}")
            return cursor.fetchone()[0]
        finally:
            conn.close()

    def list_tables(self) -> list[str]:
        """Returns names of all tables currently in the database."""
        conn = self._connect()
        try:
            cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
            tables = [row[0] for row in cursor.fetchall()]
        finally:
            conn.close()
        return tables

    def execute_query(self, query: str) -> list[dict]:
        """
        Executes a SELECT query and returns rows as a list of dicts.
        Only SELECT statements are allowed — anything else is rejected
        before it ever touches the database.
        """
        cleaned = query.strip().rstrip(";").strip()

        if not cleaned.lower().startswith("select"):
            raise ValueError("Only SELECT queries are allowed.")

        # If the query doesn't already have a limit, apply your own safety cap.
        if 'limit' not in cleaned.lower():
            cleaned = f"{cleaned} LIMIT {self.MAX_RESULT_ROWS}"

        conn = self._connect()
        """
        Standard SQLite query results come as tuples (like `(1, "John", 85.5)`), making it unclear which value corresponds to which column. By using a row factory, we can create dictionaries (like `{"id": 1, "name": "John", "percentage": 85.5}`), which makes it very easy to convert the data to JSON and feed it to an LLM.
        """
        conn.row_factory = sqlite3.Row  
        try:
            cursor = conn.execute(cleaned)
            rows = cursor.fetchall()
            return [dict(row) for row in rows]
        finally:
            conn.close()

    def remove_table(self, table_name: str) -> None:
        conn = self._connect()
        try:
            conn.execute(f"DROP TABLE IF EXISTS {self._sanitize_name(table_name)}")
            conn.commit()
        finally:
            conn.close()


sqlite_db = SQLiteService()